POST http://localhost:4242/api/pergunta
Content-Type: application/json

{
    "id": 1,
    "alternativa_a": "A velocidade da luz nesse meio é 1,2 vezes mais lenta do que no vácuo.",
    "alternativa_b": "A velocidade da luz nesse meio é 1,2 vezes mais rápida do que no vácuo.",
    "alternativa_c": "A velocidade da luz nesse meio é igual à velocidade da luz no vácuo.",
    "alternativa_d": "A velocidade da luz nesse meio depende da velocidade de seu observador",
    "questao": "A luz branca incide sobre um meio transparente cujo índice de refração é igual a 1,2. Assinale a alternativa correta em relação à velocidade da luz nesse meio:",
    "imagem": "https://static.sciencelearn.org.nz/images/images/000/000/049/embed/Refraction-of-light-in-water20150805-30610-expmepedited.png?1674163623"

}

###
GET http://localhost:4242/api/pergunta

###
GET http://localhost:4242/api/pergunta/6654b3bd2f5a362826ece6c5

###
DELETE http://localhost:4242/api/pergunta/6654b3bd2f5a362826ece6c5

###
PUT http://localhost:4242/api/6654b3bd2f5a362826ece6c1
Content-Type: application/json

{
    "id": 2,
    "alternativa_a": "A velocidade da luz nesse meio é 1,2 vezes mais lenta do que no vácuo.",
    "alternativa_b": "A velocidade da luz nesse meio é 1,2 vezes mais rápida do que no vácuo.",
    "alternativa_c": "A velocidade da luz nesse meio é igual à velocidade da luz no vácuo.",
    "alternativa_d": "A velocidade da luz nesse meio depende da velocidade de seu observador",
    "questao": "A luz branca incide sobre um meio transparente cujo índice de refração é igual a 1,2. Assinale a alternativa correta em relação à velocidade da luz nesse meio:",
    "imagem": "https://static.sciencelearn.org.nz/images/images/000/000/049/embed/Refraction-of-light-in-water20150805-30610-expmepedited.png?1674163623"

}

###
POST http://localhost:4242/api/coordenador
Content-Type: application/json

{
    "login": "LuizRicardo",
    "senha": "sqlmaster123"
}

###
GET http://localhost:4242/api/coordenador

###
GET http://localhost:4242/api/coordenador/LuizRicardo

###
DELETE http://localhost:4242/api/coordenador/LuizRicardo

###
PUT http://localhost:4242/api/coordenador/LuizRicardo
Content-Type: application/json

{
    "login": "LuizRicardo",
    "senha": "sqlmaster3224"
}
